server:
  port: 5002

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/accountDB
    username: postgres
    password: postgrespassword

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false

